apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-default-app-2023-10-27-1698392111087"

  links:
    - url: https://github.com/RohanAwasthi/aws-elasticbeanstalk-20231027073511
      title: "my-default-app-2023-10-27-1698392111087"
      icon: code

  labels:
    system: web-apps
    trackid: "aws-elasticbeanstalk-20231027073511"
    environmentname: myenv-python

  tags:
    - python
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-my-default-app-2023-10-27-1698392111087'
    github.com/project-slug: RohanAwasthi/aws-elasticbeanstalk-20231027073511
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/ebs-sample-python-application
    sonarqube.org/project-key: 'python-app/aws-elb-python'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "group:default/ey"
